/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCollapse: typeof import('element-plus/es')['ElCollapse']
    ElCollapseItem: typeof import('element-plus/es')['ElCollapseItem']
    ElIcon: typeof import("element-plus/es")["ElIcon"]
    ElInput: typeof import("element-plus/es")["ElInput"]
    QIcon: typeof import('./src/components/q-icon/index.vue')['default']
    QSearch: typeof import('./src/components/element/q-search/index.vue')['default']
    QSearchSet: typeof import('./src/components/element/q-search/q-search-set.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
